### ISSUE TITLE
Allow selection of multiple items in the list

### ISSUE THREAD

**Issue by Vybo** [deszip/Cleaner-Tracker#1]
Feature suggestion: I'd like to select multiple simulators at once to clean using CMD/SHIFT+Click. As far as I know, it is not possible at the moment.

**Comment by deszip** [comment]
Hi @Vybo , thanks for reaching out.

You actually can select multiple items in any module (see screenshot below). 
<img width="1276" alt="Screenshot 2024-01-16 at 21 07 29" src="https://github.com/deszip/Cleaner-Tracker/assets/432462/e959dce8-5003-4d05-bebb-1eb8be973d8c">

CMD+Shift+Click does not work, right. Selecting row just highlights it and does not add to items list to be removed. To add items you just click on a checkmark on the left. So I doubt it makes sense to allow multiple selection.

Did I get it right? If you can describe a case where you need a multiple select would be awesome.

**Comment by Vybo** [comment]
@deszip My use case is to select the last 20 Simulators, for example. As of now, I'd have to click the checkbox 20 times before I could clean them. My feature request is specifically about allowing me to select them all at once for cleaning, which would speed things up significantly.

If using keyboard shortcuts to manage the checkboxes directly is not acceptable, my suggestion would be to allow multiple highlights using the keyboard and then providing "select for cleanup" for the highlighted items. That would check them for cleaning so the user doesn't decheck what they already checked elsewhere.

**Comment by deszip** [comment]
Oh, now got your idea. Makes sense, I think we can allow selection by clicking item, closer to native macOS behaviour. This will allow to use both shortcuts and context menu.

Will add to the next update.

**Comment by deszip** [comment]
@Vybo Please take a look at recent update (build 746). It has an action in context menu for adding and removing selected items. Also you can use shift+click / cmd+click and cmd+a for items multiple selection.

**Comment by Vybo** [comment]
Thank you, that's awesome! Works exactly as I would expect and helps a lot!

**Comment by deszip** [comment]
Appreciate your feedback!
